sudo: false
language: python
python:

  - "3.7"
install: pip install tox-travis numpy pytest-cov codecov sklearn scipy

script:
  tox

after_success:
  - codecov

#deploy:
#  provider: pypi
#  user: "seninp"
#  password:
#    secure: "ko6k7dTrXb6x53Eipa9nQ1HnewD3SM7jeWw7CYVYWL11xjc5C2+CAv6vNIlD+HfXJbcQtljNUm7SlBDN5GJdBXY5S13/R9gKlqN8N+HZ29d7cBwmYuKaQglKLxpSaAajDHsqc+h/QeDEuvJGRcmdnINxE4MkfJU981/0lbwEPSDtaQaMletQQaBol1BeJKmJDK/kxulPX+2AwCsKS/+o3FMnu+OhwgFjk589dTLmKpuPEpJBpG2ItHe/iWw9qydXE8wSm1wmrSx4A0QcNZOE19iaMxo3GuiQxqMFCtdQcoogxsX4CCxd6MxcjqPvTYHCIZCcRQFak3dLBRqF9wEIL/mz3nQ7ZTXPFNDEFSQD6om5ni9TnqEybMtNYR2QKu4fUhs5dG0y+5HxACyw7nWdLx0Wf6SfxjqpyDfd7rsSmPIUtKjzihgdWPSpESqP0TiYR7btZmue6ympQGcbeTSJ/cHOv+oL+mXhjdU/cRM625vN29ogXG8FwzDXICca4sKtEtXL/utAxF3fEUYkJecAP1p71+99Jhq2h/fbayAjViVe7m7H9fvahkgFT5MLQfiBIVWu6DD2+vnZJoYWbu6fG8HZTRTjfBGVXIiDVusxEKMc77bCJtHkM+McxCmG1gm+gYhiAp44BmidqfryKfaHQi2THfHRs1VpsbBb5FjKjw0="

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
